# This is a prototype profile declarative manifest in TOML format,
# supporting comments and the ability to invoke "shellHook" commands
# upon profile activation. See the flox(1) man page for more details.

# [environment]
#   LANG = "en_US.UTF-8"
#   LC_ALL = "$LANG"
#
# [aliases]
#   gg = "git grep"
#
# [hooks]
#   sayhi = """
#     echo "Supercharged by flox!" 1>&2
#   """
#
# Edit below the "--- >8 ---" delimiter to define the list of packages to
# be installed, but note that comments and the ordering of packages will
# *not* be preserved with updates.

# ------------------------ >8 ------------------------
[packages]
  [packages."elixir"]
  channel = "nixpkgs-flox"
  stability = "stable"

  [packages."flox-prerelease"]
  channel = "flox"
  stability = "stable"

  [packages."fzf"]
  channel = "nixpkgs-flox"
  stability = "stable"

  [packages."jq"]
  channel = "nixpkgs-flox"
  stability = "stable"

  [packages."python3"]
  channel = "nixpkgs-flox"
  stability = "stable"

  [packages."tree"]
  channel = "nixpkgs-flox"
  stability = "stable"

  [packages."legacyPackages.x86_64-linux.vscode"]
  originalUrl = "flake:nixpkgs"
  attrPath = "legacyPackages.x86_64-linux.vscode"

